[book]
authors = ["TYIC", "Myster7494"]
language = "zh-Hant-TW"
multilingual = false
src = "src"
title = "TYIC textbook"

[build]
use-default-preprocessors = false

[output.html]
additional-js = ["theme/fzf.umd.js", "theme/elasticlunr.js","theme/pagetoc.js"]
additional-css = ["theme/pagetoc.css"]

[preprocessor.links]

[preprocessor.katex]
after = ["links"]
