[book]
authors = ["TYIC", "Myster7494"]
language = "zh-Hant-TW"
multilingual = false
src = "src"
title = "TYIC textbook"

[build]
use-default-preprocessors = false

[preprocessor.links]

[preprocessor.katex]
after = ["links"]
