[book]
authors = ["TYIC", "Myster7494"]
language = "zh-Hant-TW"
multilingual = false
src = "src"
title = "TYIC textbook"

[build]
use-default-preprocessors = false

[output.html]
additional-js = ["extra/fzf.umd.js", "extra/elasticlunr.js", "extra/pagetoc.js"]
additional-css = ["extra/pagetoc.css"]

[preprocessor.links]

[preprocessor.katex]
after = ["links"]
